url: https://bpocit.github.io
baseurl: /website/

# Site settings
title: BPoCiT Study Group
email: your-email@domain.com
description: "A Black and People of Color Study Group for Web Development"


# Team names, titles and social links
people:
- name: BPoCiT
  pic: 1
  position: Study Group
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/bpocit

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
