url: https://1000miles.github.io
baseurl: /bpocit-website

# Site settings
title: BPoCiT Study Group
email: bpocit@splendits.de
description: "A Black and People of Color Study Group for Web Development"

defaults:
  scope:
      path: ""
      type: page
  values:
      layout: default

# Directories
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes


# Team names, titles and social links
people:
- name: BPoCiT Study Group
  pic: 1
  position: Study Group
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/bpocit
  - title: twitter
    url: #

# Build settings
markdown: kramdown
permalink: pretty
